---
title: "Orkumál"
author: 
    -   name: "Brynjólfur Gauti Guðrúnar Jónsson"
        url: "https://twitter.com/bgautijonsson"
        affiliation: "Tölfræði, Raunvísindadeild Háskóla Íslands"
        affiliation-url: "https://www.hi.is/tolfraedi_0"
date: today
format: 
    html:
        code-fold: true
        toc: true
        toc-location: right
        toc-title: Efnisyfirlit
editor: source
theme: flatly
title-block-banner: true
standalone: true
self-contained: true
---


```{r}
#| include: false

library(cowplot)
library(tidyverse)
library(scales)
library(pxweb)
library(ggthemes)
library(kableExtra)
library(gganimate)
library(lubridate)
library(geomtextpath)
library(ggtext)
library(here)
library(readxl)
library(janitor)
```

# Gögn

```{r}
d <- read_csv("https://raw.githubusercontent.com/owid/energy-data/master/owid-energy-data.csv") |> 
    select(country, year, 
           contains("gdp"), contains("pop"), 
           fossil_share_energy, fossil_share_elec, fossil_energy_per_capita,
           renewables_share_elec, renewables_share_energy, 
           energy_per_capita, per_capita_electricity,
           oil_prod_per_capita,
           greenhouse_gas_emissions,
           carbon_intensity_elec,
           low_carbon_energy_per_capita) |> 
    mutate(gdp_per_capita = gdp / population,
           greenhouse_per_capita = greenhouse_gas_emissions / population * 1e6 * 1e5,
           gdp_per_greenhouse = gdp / greenhouse_gas_emissions,
           high_carbon_energy_per_capita = energy_per_capita - low_carbon_energy_per_capita)
```

# Orka og framleiðsla

```{r}
start <- d |> filter(year >= 1980, energy_per_capita > 0) |> pull(energy_per_capita) |> min(na.rm = T)
end <- d |> filter(year >= 1980, energy_per_capita > 0) |> pull(energy_per_capita) |> max(na.rm = T)

min_gdp <- d |> filter(year >= 1980) |> pull(gdp_per_capita) |> min(na.rm = T)
max_gdp <- d |> filter(year >= 1980) |> pull(gdp_per_capita) |> max(na.rm = T)

plot_dat <- crossing(energy_per_capita = seq(log(start), log(end), length = 100) |> exp(),
                     ratio = c(0.25, 0.5, 1, 2, 4)) |> 
    mutate(gdp_per_capita = ratio * energy_per_capita) |> 
    filter(gdp_per_capita < max_gdp * 1.1,
           gdp_per_capita > min_gdp)

add_preds <- function(data, ...) {
    m <- lm(log(gdp_per_capita) ~ log(energy_per_capita), data = data)
    data$pred <- exp(predict(m))
    
    data
}


p <- d |> 
    select(gdp_per_capita, energy_per_capita, country, year) |> 
    drop_na() |> 
    filter(year >= 1980, country != "World") |> 
    group_by(country) |>
    filter(any(year == 1980)) |>
    ungroup() |> 
    group_by(year) |> 
    group_modify(add_preds) |> 
    ungroup() |> 
    ggplot(aes(energy_per_capita, gdp_per_capita,
               colour = (country == "Iceland"),
               size = (country == "Iceland"),
               alpha = (country == "Iceland"))) +
    geom_line(
        data = plot_dat,
        aes(energy_per_capita, gdp_per_capita, group = ratio),
        inherit.aes = FALSE
    ) +
    geom_text(data = plot_dat |> 
                  group_by(ratio) |> 
                  filter(energy_per_capita == max(energy_per_capita)) |> 
                  ungroup(),
              aes(x = energy_per_capita,
                  y = gdp_per_capita,
                  label = 1 / ratio),
              inherit.aes = FALSE, hjust = 0, vjust = 0, 
              nudge_x = 0.03,
              nudge_y = 0.03) +
    geom_line(aes(y = pred), lty = 2, col = "black", size = 1) +
    geom_point() +
    # geom_rangeframe() +
    scale_x_log10(labels = label_number(suffix = " kWh", big.mark = ".", decimal.mark = ",")) +
    scale_y_log10(labels = label_number(suffix = "$", big.mark = ".", decimal.mark = ",")) +
    scale_colour_manual(values = c("#969696", "#4292c6")) +
    scale_size_manual(values = c(2.5, 4)) +
    scale_alpha_manual(values = c(0.7, 1)) +
    theme_half_open(font_size = 12) +
    theme(legend.position = "none",
          plot.title = element_markdown(face = "plain")) +
    labs(x = "Orkuframleiðsla á mann",
         y = "Landsframleiðsla á mann",
         title = "Þróun orku- og landsframleiðslu á <b style='color:#4292c6'>Íslandi</b> samanborið við <b style='color:#969696'>heiminn</b>",
         subtitle = str_c("Heilar línur sýna mismunandi hlutföll orku- / landsframleiðslu",
                          "\n",
                          "Brotin lína sýnir fylgni stærðanna á heimsvísu",
                          "\n",
                          "Ár: {frame_time}"),
         caption = "Kóði og gögn: https://github.com/bgautijonsson/orkumal") +
    transition_time(as.integer(year)) +
    ease_aes("cubic-in-out")

p_vid <- animate(p, width = 12, height = 0.5 * 12, unit = "in", res = 150, fps = 25, duration = 15,
                 renderer = ffmpeg_renderer(format = "mp4"))

anim_save(filename = "throun_orku_framleidslu.mp4", animation = p_vid)
```

# Gróðurhúsalofttegundir og framleiðsla

```{r}
start <- d |> 
    filter(year >= 2000, greenhouse_per_capita > 0) |> 
    pull(greenhouse_per_capita) |>
    min(na.rm = T)
end <- d |>
    filter(year >= 2000, greenhouse_per_capita > 0) |> 
    pull(greenhouse_per_capita) |> 
    max(na.rm = T)

min_gdp <- d |> 
    filter(year >= 2000) |> 
    pull(gdp_per_capita) |> 
    min(na.rm = T)
max_gdp <- d |> 
    filter(year >= 2000) |> 
    pull(gdp_per_capita) |>
    max(na.rm = T)

plot_dat <- crossing(greenhouse_per_capita = seq(log(start),
                                                 log(end), 
                                                 length = 500) |> exp(),
                     ratio = c(1/16, 1/8, 1/4, 1/2, 1, 2, 4)) |> 
    mutate(gdp_per_capita = ratio * greenhouse_per_capita) |> 
    filter(gdp_per_capita <= max_gdp * 1.1,
           gdp_per_capita >= min_gdp)

add_preds <- function(data, ...) {
    m <- lm(log(gdp_per_capita) ~ log(greenhouse_per_capita), data = data)
    data$pred <- exp(predict(m))
    
    data
}


p <- d |> 
    select(gdp_per_capita, greenhouse_per_capita, country, year) |> 
    drop_na() |> 
    filter(year >= 2000, country != "World") |> 
    group_by(country) |>
    filter(any(year == 2000), all(greenhouse_per_capita > 0)) |>
    ungroup() |> 
    group_by(year) |> 
    group_modify(add_preds) |> 
    ungroup() |> 
    ggplot(aes(greenhouse_per_capita, gdp_per_capita,
               colour = (country == "Iceland"),
               size = (country == "Iceland"),
               alpha = (country == "Iceland"))) +
    geom_line(
        data = plot_dat,
        aes(greenhouse_per_capita, gdp_per_capita, group = ratio),
        inherit.aes = FALSE
    ) +
    geom_text(data = plot_dat |> 
                  group_by(ratio) |> 
                  filter(greenhouse_per_capita == max(greenhouse_per_capita)) |> 
                  ungroup(),
              aes(x = greenhouse_per_capita,
                  y = gdp_per_capita,
                  label = 1 / ratio),
              inherit.aes = FALSE, hjust = 0, vjust = 0, 
              nudge_x = 0.03,
              nudge_y = 0.03) +
    geom_line(aes(y = pred), lty = 2, col = "black", size = 1) +
    geom_point() +
    # geom_rangeframe() +
    scale_x_log10(labels = label_number(big.mark = ".", decimal.mark = ",")) +
    scale_y_log10(labels = label_number(suffix = "$", big.mark = ".", decimal.mark = ",")) +
    scale_colour_manual(values = c("#969696", "#4292c6")) +
    scale_size_manual(values = c(2.5, 4)) +
    scale_alpha_manual(values = c(0.7, 1)) +
    theme_half_open(font_size = 12) +
    theme(legend.position = "none",
          plot.title = element_markdown(face = "plain")) +
    labs(x = "Gróðurhúsalofttegundir (Milljörð tonna á 100.000 íbúa)",
         y = "Landsframleiðsla á mann",
         title = "Þróun útblásturs gróðurhúsalofttegunda og landsframleiðslu á <b style='color:#4292c6'>Íslandi</b> samanborið við <b style='color:#969696'>heiminn</b>",
         subtitle = str_c("Heilar línur sýna mismunandi hlutföll gróðushúsalofttegunda / landsframleiðslu",
                          "\n",
                          "Brotin lína sýnir fylgni stærðanna á heimsvísu",
                          "\n",
                          "Ár: {frame_time}"),
         caption = "Kóði og gögn: https://github.com/bgautijonsson/orkumal") +
    transition_time(as.integer(year)) +
    ease_aes("cubic-in-out")

p_vid <- animate(p, width = 12, height = 0.5 * 12, unit = "in", res = 150, 
                 fps = 25, duration = 10,
                 renderer = ffmpeg_renderer(format = "mp4"))

anim_save(filename = "throun_grodurhusa_framleidslu.mp4", animation = p_vid)
```


# Jarðefnaeldsneyti og framleiðsla

```{r}
start <- d |> 
    filter(year >= 1990, fossil_energy_per_capita > 0) |> 
    pull(fossil_energy_per_capita) |>
    min(na.rm = T)
end <- d |>
    filter(year >= 1990, fossil_energy_per_capita > 0) |> 
    pull(fossil_energy_per_capita) |> 
    max(na.rm = T)

min_gdp <- d |> 
    filter(year >= 1990) |> 
    pull(gdp_per_capita) |> 
    min(na.rm = T)
max_gdp <- d |> 
    filter(year >= 1990) |> 
    pull(gdp_per_capita) |>
    max(na.rm = T)

plot_dat <- crossing(fossil_energy_per_capita = seq(log(start),
                                                 log(end), 
                                                 length = 500) |> exp(),
                     ratio = c(1/4, 1/2, 1, 2, 4)) |> 
    mutate(gdp_per_capita = ratio * fossil_energy_per_capita) |> 
    filter(gdp_per_capita <= max_gdp * 1.1,
           gdp_per_capita >= min_gdp)

add_preds <- function(data, ...) {
    m <- lm(log(gdp_per_capita) ~ log(fossil_energy_per_capita), data = data)
    data$pred <- exp(predict(m))
    
    data
}


p <- d |> 
    select(gdp_per_capita, fossil_energy_per_capita, country, year) |> 
    drop_na() |> 
    filter(year >= 1990, country != "World") |> 
    group_by(country) |>
    filter(all(gdp_per_capita > 0), 
           all(fossil_energy_per_capita > 0),
           any(year == 1990)) |> 
    ungroup() |> 
    group_by(year) |> 
    group_modify(add_preds) |> 
    ungroup() |> 
    ggplot(aes(fossil_energy_per_capita, gdp_per_capita,
               colour = (country == "Iceland"),
               size = (country == "Iceland"),
               alpha = (country == "Iceland"))) +
    geom_line(
        data = plot_dat,
        aes(fossil_energy_per_capita, gdp_per_capita, group = ratio),
        inherit.aes = FALSE
    ) +
    geom_text(data = plot_dat |> 
                  group_by(ratio) |> 
                  filter(fossil_energy_per_capita == max(fossil_energy_per_capita)) |> 
                  ungroup(),
              aes(x = fossil_energy_per_capita,
                  y = gdp_per_capita,
                  label = 1 / ratio),
              inherit.aes = FALSE, hjust = 0, vjust = 0, 
              nudge_x = 0.03,
              nudge_y = 0.03) +
    geom_line(aes(y = pred), lty = 2, col = "black", size = 1) +
    geom_point() +
    # geom_rangeframe() +
    scale_x_log10(labels = label_number(suffix = " kWh", big.mark = ".", decimal.mark = ",")) +
    scale_y_log10(labels = label_number(suffix = "$", big.mark = ".", decimal.mark = ",")) +
    scale_colour_manual(values = c("#969696", "#4292c6")) +
    scale_size_manual(values = c(2.5, 4)) +
    scale_alpha_manual(values = c(0.7, 1)) +
    theme_half_open(font_size = 12) +
    theme(legend.position = "none",
          plot.title = element_markdown(face = "plain")) +
    labs(x = "Jarðefnaeldsneytisnotkun á mann",
         y = "Landsframleiðsla á mann",
         title = "Þróun notkunar jarðefnaeldsneytis og landsframleiðslu á <b style='color:#4292c6'>Íslandi</b> samanborið við <b style='color:#969696'>heiminn</b>",
         subtitle = str_c("Heilar línur sýna mismunandi hlutföll jarðefnaeldsneytis / landsframleiðslu",
                          "\n",
                          "Brotin lína sýnir fylgni stærðanna á heimsvísu",
                          "\n",
                          "Ár: {frame_time}"),
         caption = "Kóði og gögn: https://github.com/bgautijonsson/orkumal") +
    transition_time(as.integer(year)) +
    ease_aes("cubic-in-out")

p_vid <- animate(p, width = 12, height = 0.5 * 12, unit = "in", res = 150, fps = 25,
                 duration = 15,
                 renderer = ffmpeg_renderer(format = "mp4"))

anim_save(filename = "throun_jardefna_framleidslu.mp4", animation = p_vid)
```


# Raða eftir jarðefnaeldsneyti og gdp

## 2018

```{r, fig.width = 10, fig.asp = 1}
p <- d |> 
    filter(year == 2018) |> 
    select(country, fossil_energy_per_capita, gdp_per_capita) |> 
    drop_na() |> 
    mutate(fossil_per_gdp = fossil_energy_per_capita / gdp_per_capita,
           country = fct_reorder(country, fossil_per_gdp)) |> 
    ggplot(aes(fossil_per_gdp, country,
               fill = country == "Iceland")) +
    geom_col() +
    scale_fill_manual(values = c("#969696", "#4292c6")) +
    theme_half_open() +
    theme(legend.position = "none") +
    coord_cartesian(expand = FALSE) +
    labs(x = "Notkun jarðefnaeldsneytis (kWh) deilt með landsframleiðslu ($)",
         y = NULL,
         title = "Röðun landa eftir hlutfalli jarðefnaeldsneytis (kWh) og landsframleiðslu ($) árið 2018",
         subtitle = "Jarðefnaeldsneyti er hér olía, gas og kol",
         caption = "Kóði og gögn: https://github.com/bgautijonsson/orkumal")

ggsave(plot = p, filename = "ordered_fossil.png",
       width = 8, height = 8, scale = 1.7, bg = "white")
```

## Þróun

```{r}
countries <- c("Germany", "Iceland", "India", "New Zealand", "Norway", "Sweden")
icelandic <- c(
    "Germany" = "Þýskaland", 
    "Iceland" = "Ísland", 
    "India" = "Indland", 
    "New Zealand" = "Nýja Sjáland",
    "Norway" = "Noregur",
    "Sweden" = "Svíþjóð")


plot_dat <- d |> 
    select(year, country, fossil_energy_per_capita, gdp_per_capita) |> 
    drop_na() |> 
    mutate(fossil_per_gdp = fossil_energy_per_capita / gdp_per_capita) |> 
    filter(year >= 1980) |> 
    mutate(alpha = country %in% countries,
           colour = fct_other(country,
                              keep = countries,
                              other_level = "Other"),
           y = fossil_per_gdp,
           y = case_when(country == "Iceland" ~ y + 0,
                         country == "New Zealand" ~ y - 0.05,
                         country == "India" ~ y + 0.05,
                         country == "Sweden" ~ y + 0.02,
                         country == "Norway" ~ y - 0.02,
                         TRUE ~ y))

p <- plot_dat |> 
    ggplot(aes(year, fossil_per_gdp,
               colour = colour,
               alpha = alpha)) +
    geom_line(aes(group = country, size = alpha)) +
    geom_text(data = plot_dat |> 
                  filter(country %in% countries,
                         year == max(year)) |> 
                  mutate(country = icelandic[country]),
              aes(y = y, label = country),
              hjust = 0, nudge_x = 0.1, size = 4) +
    geom_rangeframe(colour = "black", alpha = 1) +
    scale_x_continuous(expand = expansion(),
                       limits = c(1980, 2018.5),
                       breaks = c(1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2018)) +
    scale_y_continuous() +
    scale_colour_manual(values = c("#ff7f00", 
                                   "#377eb8",
                                   "#4daf4a",
                                   "black", 
                                   "#e41a1c", 
                                   "#ffed6f",
                                   "grey")) +
    scale_alpha_manual(values = c(0.3, 1)) +
    scale_size_manual(values = c(0.5, 1)) +
    theme_tufte() +
    theme(legend.position = "none",
          plot.title = element_text(face = "bold")) +
    coord_cartesian(ylim = c(0, 2),
                    xlim = c(1980, 2021.9),
                    expand = F) +
    labs(x = NULL,
         y = NULL,
         title = "Þróun hlutfalls jarðefnaeldsneytisnotkunar (kWh) og landsframleiðslu ($) árin 1980 - 2018",
         subtitle = "Jarðefnaeldsneyti er hér olía, gas og kol",
         caption = "Kóði og gögn: https://github.com/bgautijonsson/orkumal")

ggsave(plot = p, filename = "throun_fossil.png",
       width = 8, height = 0.5 * 8, scale = 1.3, bg = "white")
```

